### ISSUE TITLE
Support for display of imported data

### ISSUE THREAD

**Issue by elfring** [okbob/pspg#103]
[Data can be imported from external files into a database table](https://www.postgresql.org/docs/11/sql-copy.html "Copy data between a file and a table").
Would you like to support this operation by your tool anyhow?

**Comment by okbob** [comment]
pá 13. 9. 2019 v 8:50 odesílatel Markus Elfring <notifications@github.com>
napsal:

> Do you know where is this documentation?
>
> Do you find the documentation for supported PostgreSQL output data formats
> sufficient?
>
https://www.postgresql.org/docs/11/app-psql.html

The SQL databases usually doesn't describe formatted output - because it is
visible - and only minimum application are working with post processed
output - I know `pspg` only.

So I don't remember any doc where formatted output is documented - for any
SQL database that I know.

You can find documentation for communication API, but it is not relevant
for pspg.

Attention - this is pretty different from NoSQL databases - if you have
experience with these databases, the SQL world is very different

**Comment by elfring** [comment]
>So I don't remember any doc where formatted output is documented …

Would any contributors like to improve this situation anyhow?

**Comment by okbob** [comment]
pá 13. 9. 2019 v 9:18 odesílatel Markus Elfring <notifications@github.com>
napsal:

> So I don't remember any doc where formatted output is documented …
>
> Would any contributors like to improve this situation anyhow?
>
Probably for nobody this is a issue. Usually this topic is not interesting.

**Comment by elfring** [comment]
:crystal_ball: Under which circumstances will the safe collaboration of involved programs become more interesting?

**Comment by okbob** [comment]
pá 13. 9. 2019 v 9:30 odesílatel Markus Elfring <notifications@github.com>
napsal:

> 🔮 Under which circumstances will the safe collaboration of involved
> programs become more interesting?
>

????
