### ISSUE TITLE
Scrolling with cursor freezes randomly for seconds

### ISSUE THREAD

**Issue by thorstenkampe** [okbob/pspg#158]
Starting with version 4.2.0 scrolling with the up or down cursor (pressing the cursor key and keeping the key pressed) freezes  randomly. It scrolls a few lines and then stalls for a few seconds. It only happens on Cygwin (Linux not affected).

**Comment by okbob** [comment]
Hi

so 6. 3. 2021 v 23:04 odesílatel Thorsten Kampe <notifications@github.com>
napsal:

> Starting with version 4.2.0 scrolling with the up or down cursor (pressing
> the cursor key and keeping the key pressed) freezes randomly. It scrolls a
> few lines and then stalls for a few seconds. It only happens on Cygwin
> (Linux not affected).
>
Please, can you check the last commit and --no-sleep option?

I think there is only one related possibility - there is new protection
against flickering - the pspg ensures minimal time between two screen
refreshes now. Sometimes the frequency of refreshes can be too fast, and a)
there is flickering - only part of the screen is physically drawn (because
ncurses and terminal applications miss hw synchronization) and sometimes
the terminal is overloaded.

I pushed the new option "--no-sleep", that disables this protection.
Please, can you check it. It is the simple solution. Another possibility is
identification of commits that does this issue. But I do not have a
computer with a window and cygwin.

**Comment by thorstenkampe** [comment]
`--no-sleep` fixes the issue on Cygwin, thanks.

**Comment by okbob** [comment]
ne 7. 3. 2021 v 7:26 odesílatel Thorsten Kampe <notifications@github.com>
napsal:

> --no-sleep fixes the issue on Cygwin, thanks.
>
super - thank you for check and for report

Pavel

**Comment by okbob** [comment]
release 4.3.1 released
