### ISSUE TITLE
Clearer + more visible installation instructions?

### ISSUE THREAD

**Issue by karlhorky** [okbob/pspg#234]
Hi there, thanks for this project! Looks amazing.

I would like to recommend it to our students, but the installation + configuration guide is a bit spread out in the readme.

Would you be open to:

1. Consolidating the installation + configuration parts (only 1 single guide to follow, not multiple)
2. Making it more visible in the readme (eg. moving it up to directly below a brief introduction of what the tool is and what it can do

Would be great and I would imagine would help with more users installing this great tool.

**Comment by okbob** [comment]
Maybe as author of pspg I living in own bubble, because installation is just `sudo dnf install pspg` and necessary configuration is `export PSQL_PAGER=pspg`.  But sure, I invite any PR to readme to be better for beginners or students (I am not sure, if I able to do - I have minimal language skills in English language, and I am little bit isolated from students or beginners now, so I maybe I don't understand what they prefer.

**Comment by okbob** [comment]
I wrote new section 3c336951585bf3253bd47375a7842af89851dc1a

**Comment by karlhorky** [comment]
@okbob nice! What about also including `brew install pspg` (macOS) in the shorter installation instructions section?

**Comment by okbob** [comment]
so 30. 12. 2023 v 1:47 odesílatel Karl Horky ***@***.***>
napsal:

> @okbob <https://github.com/okbob> nice! What about also including brew
> install pspg (macOS) in the shorter installation instructions section?
>

it is there already

https://github.com/okbob/pspg#homebrew-for-linux--macos

**Comment by okbob** [comment]
d7e1a581258c1c08d69fddbca07513fb35e4f2c2

**Comment by karlhorky** [comment]
Nice, thanks!

These new commits seem to resolve this issue, so I'm closing it now.
