### ISSUE TITLE
describe what an "alternate screen" is for -X option

### ISSUE THREAD

**Issue by mzagrabe** [okbob/pspg#47]
Thanks for pspg. I've just started using it and it looks promising.

I was reading through the man page and also the recommended .psqlrc configs and noticed "-X" in the configuration. I don't know what alternate screen the documentation is referring to. I've looked at the source code and can't make sense of it either.

Would you consider expanding the documentation a bit with regards to "alternate screen" ?

Thanks again!

-m

**Comment by okbob** [comment]
Alternate screen is terminal feature - that allows to switch back to original content before application start. Lot of applications uses alternate screen by default, and when finish, then screen is restored. `less`  has option `-X ` or `--no-init` to disable this alternate screen and draw directly to original screen. I had a problem do same thing with ncurses application, so I had to emulate this feature. When ncurses are closed, then I redraw the content again - so you cannot to find any alternate screen related code in pspg. Although I directly don't use alternate screen feature, I used it in help and doc, because it is well known term.
