### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by depesz** [okbob/pspg#74]
Hi,
I just switched myself to pspg - looks great. I could use three things, though:

1. ability to hide columns. Something along the line of current freeze, but instead hide them.
2. ability to define our own themes, preferably using full 256 colors, and not only base 16.
3. ability to add special syntax-highlights and substitutions.

#3 might be most complicated, so simple example:
I'd like to be able to say, that if given column value is 'f' change it 'false', and color as red, and if it's 't' then change it to green "ok".

Is that achievable?

**Comment by okbob** [comment]
Hi

2018-09-04 12:28 GMT+02:00 Hubert depesz Lubaczewski <
notifications@github.com>:

> Hi,
> I just switched myself to pspg - looks great. I could use three things,
> though:
>
>    1. ability to hide columns. Something along the line of current
>    freeze, but instead hide them.
>    2. ability to define our own themes, preferably using full 256 colors,
>    and not only base 16.
>    3. ability to add special syntax-highlights and substitutions.
>
> #3 <https://github.com/okbob/pspg/issues/3> might be most complicated, so
> simple example:
> I'd like to be able to say, that if given column value is 'f' change it
> 'false', and color as red, and if it's 't' then change it to green "ok".
>
> Is that achievable?
>
1. is possible - with some bitmap of hidden columns - but the
transformations from original to display will be much more complex. When I
started work on pspg I found how UTF8 is complex - the char can have more
bytes (that was not new for me), but the char can have 1, 1.5 or two
display width (that was new for me). More difficult is interface - there
are only line cursor - not column cursor

Maybe it needs some deeper change - now pspg is just pager - and data are
stored internally in original form. Storing data in some column format can
simplify implementation of similar requests.

2. is relatively simple - just write code for loading theme from files.

3. is hard now - the colouring is not trivial now - there is some state
machine that choose colors for  data, borders, cursors, search pattern,
marked lines, searched lines. With new possible states, the state machine
will be much more complex, and it needs redesign - significant redesign.

I don't know how much time I'll have for work on pspg. Now I finished some
stage, and I plan to work on different projects.

If you have some good theme, I can merge it directly to code. It will be
faster than waiting for implementation of  generic theme support. Support
of 256 colors is not difficult task. I didn't it, because I had not good
theme.

Regards

Pavel

**Comment by depesz** [comment]
First of all - thanks for quick reply.

Points:

1. Not sure why would we need column cursor? We could just do something like "h" (hide) 1-9
2. yeah - c is not my forte, so tackling this is "a bit" above my skills
3. I definitely understand.

Will try to create some nice-ish theme, and send you pull request with it.

**Comment by okbob** [comment]
2018-09-04 14:03 GMT+02:00 Hubert depesz Lubaczewski <
notifications@github.com>:

> First of all - thanks for quick reply.
>
> Points:
>
>    1. Not sure why would we need column cursor? We could just do
>    something like "h" (hide) 1-9
>
> something like skip first n columns? Then the implementation can be very
simple, but I don't see benefit for users.


>
>    1. yeah - c is not my forte, so tackling this is "a bit" above my
>    skills
>    2. I definitely understand.
>
> Will try to create some nice-ish theme, and send you pull request with it.
>
great :). It should not be hard - the theme support should be almost well
isolated.

https://github.com/okbob/pspg/blob/master/src/themes.c

This version of pspg is stil +/- prototype. It is experiment. I am learning
ncurses, and I am learning to write some more rich TUI app.

Now, I would to work on Postgres variables, and later on csv support for
pspg.

**Comment by okbob** [comment]
Today I wrote two themes, that uses more than 256 colors, so it is not problem.
