### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [okbob/pspg#99]
Would you like to add more error handling for return values from functions like the following?
- [fprintf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output") ⇒ [save_config](https://github.com/okbob/pspg/blob/39dcc0e1a3d70b9eb41e2d9470974693071dbb6b/src/config.c#L75)
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [translate_headline](https://github.com/okbob/pspg/blob/4acf688bf7d25d5365f9465fe1145424072fd23d/src/pspg.c#L338)

**Comment by okbob** [comment]
should be fixed by 41ae9ab1c286c908a931ca8fcea3833b4dc09d66

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/okbob/pspg/commit/41ae9ab1c286c908a931ca8fcea3833b4dc09d66 "Handle possible malloc and fprintf error").

* Were [any update candidates left over](https://github.com/okbob/pspg/blob/808b3794bdf4132fe68a38aa0ba501a631ebb0da/src/pspg.c#L1834 "Update candidate: show_info_wait()")?
* How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by okbob** [comment]
If somebody does this work I am not against :).

**Comment by elfring** [comment]
* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by okbob** [comment]
sorry, I don't understand ???

**Comment by elfring** [comment]
I suggest to take higher level development tools better into account for [the handling of cross-cutting concerns](https://en.wikipedia.org/wiki/Cross-cutting_concern#Examples "Description for cross-cutting concerns").

**Comment by okbob** [comment]
I don't think so it is necessary for project of pspg size. This project is my "hobby" project and I tested some my ideas - so I strongly prefer simple development as is possible (from my side). The code of pspg is not too nice - it is my first ncurses event driven application - so there is lot of things that would be done better, but mostly in abstraction layer. I don't expect any help from tools. 

The significant issue is ncurses - it is too low level API, but any others frameworks that I found are OOP or too large. Still pspg is short life application, and then should to have fast start. 

I'll be pleasured every time if somebody will try some linters on this project and will do report of bugs or security bugs, but I don't plan to use these tools by self. Just because it is not my main work and I will not use these tools every day - so I miss any motivation to learn some complex tools.

**Comment by elfring** [comment]
>I don't expect any help from tools.

I assume that you are used to a selection of development tools aready.


>, but any others frameworks that I found are OOP or too large.

**Comment by okbob** [comment]
> > I don't expect any help from tools.
> 
> I assume that you are used to a selection of development tools already.

I am not a professional coder. I work like DBA consultant, teacher or DB performance engineer. Programming is just my hobby (in this moment). Years ago  I wrote some applications in PLpgSQL, Perl, but it is long time ago.
  
> 
> > …, but any others frameworks that I found are OOP or too large.
> 
> Object- and aspect-oriented programming can be a nice combination, can't it?

I am not against these techniques - just I don't use it. I cooperate on PostgreSQL development - and it is in C with some OOP features, but it is plain and clean C. So it is a environment that I know and when I am feel comfortable.  So - I am lazy do things more sophisticated than it is necessary. 

When `pspg` has about 150kB I would not to link it with libraries longer than megabytes. But again it is because `pspg` is hobby project - I don't need to solve to economic side of this project. Else `pspg` doesn't exists or it is written very different.

> 
> > … - so I miss any motivation to learn some complex tools.
> 
> I hope that this area can be adjusted somehow.

Maybe. All depends on what a man currently works - size, language, purpose, complexity. Almost all my work is in design of things - and programming is not too complex, because I would to do simple things. But who know what will be in next days.

**Comment by okbob** [comment]
please, send any proposal for enhancing pspg code freely. You are welcome

**Comment by elfring** [comment]
Will the chances increase to integrate additional tools into your software development process?

**Comment by okbob** [comment]
It depends on maintenance overhead. I would not to break build on any platform, and I would not to spend too much time by their installation.

**Comment by elfring** [comment]
How will your change resistance (or acceptance) evolve for mentioned software areas?

**Comment by okbob** [comment]
čt 12. 9. 2019 v 9:32 odesílatel Markus Elfring <notifications@github.com>
napsal:

> How will your change resistance (or acceptance) evolve for mentioned
> software areas?
>
I don't know - I have not a idea, what I'll do next year, and what tools
I'll need.

**Comment by elfring** [comment]
I am curious if your development interests can grow in the mentioned software areas.

**Comment by okbob** [comment]
čt 12. 9. 2019 v 9:38 odesílatel Markus Elfring <notifications@github.com>
napsal:

> I am curious if your development interests can grow in the mentioned
> software areas.
>
I am a man who has not like big plans - I have a plans for next two months,
and what is later, nobody knows.

I accept the power and benefit of these tools, but how I say, almost all my
code is very small.

**Comment by elfring** [comment]
>I accept the power and benefit of these tools,

This feedback sounds promising.


>but how I say, almost all my code is very small.

At which time would you get into the mood to let any tools help you a bit more?

**Comment by okbob** [comment]
čt 12. 9. 2019 v 9:48 odesílatel Markus Elfring <notifications@github.com>
napsal:

> I accept the power and benefit of these tools,
>
> This feedback sounds promising.
>
> but how I say, almost all my code is very small.
>
> At which time would you get into the mood to let any tools help you a bit
> more?
>

have no any idea
